config/routes.rb
Rails.application.routes.draw do
  root 'streets#console'
  resources :streets

  get '/streets/new', to: 'streets#new'
  post '/streets/new', to: 'streets#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/street.rb
class Street < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController

  def console
    @streets = Street.all
  end

  def new
    @street = Street.new
  end

  def create
    @street = Street.new(street_params)
    @street.save
    respond_to :js
  end

  def show
    @street = Steet.find(params[:id])
  end

  def edit

  end

  def update

  end

  private

  def street_params
    params.require(:street).permit(:name, :borough, :left_side, :right_side, :start_time, :end_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_create_street_form.html.erb
<%= form_for :street, url: new_street_path, action: 'create' do |s| %>
<%= s.text_field :name %>
<%= s.radio_button :borough, 'Brooklyn', class: 'radio', id: 'brooklyn1' %>
<label for="brooklyn1">Brooklyn</label>
<%= s.radio_button :borough, 'Queens', class: 'radio', id: 'queens1' %>
<label for="queens1">Queens</label>
<%= s.radio_button :borough, 'Manhattan', class: 'radio', id: 'manhattan1' %>
<label for="manhattan1">Manhattan</label>
<%= s.radio_button :borough, 'Bronx', class: 'radio', id: 'bronx1' %>
<label for="bronx1">Bronx</label>
<%= s.radio_button :borough, 'Staten Island', class: 'radio', id: 'SI1' %>
<label for="SI1">Staten Island</label>
<%= s.submit class: 'btn btn-primary' %>
<% end %>

app/views/partials/_created_streets.html.erb
Palmetto St.

app/views/streets/console.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container-fluid">
  <div class="row content">
    <div class="col-md-4 col-md-navbar-left">
      <h4>Add Street</h4>
      <ul class="nav nav-pills nav-stacked">
      <%= render 'partials/create_street_form'%>
      </ul><br>
    </div>
     <div class="col-xs-2">
       <h4>Added Streets</h4>
       <%= render 'partials/created_streets'%>
    </div>
  </div>
</div>
</body>
</html>